"""empty message

Revision ID: 813ad6a8c25c
Revises: a62a6c8f0fc0
Create Date: 2023-06-11 22:41:18.582983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813ad6a8c25c'
down_revision = 'a62a6c8f0fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_planeta', sa.Integer(), nullable=True),
    sa.Column('id_personaje', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personaje'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['id_planeta'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    # ### end Alembic commands ###
